services:
  db:
    image: mysql:8.4
    container_name: mysql8
    restart: unless-stopped
    ports:
      - "3306:3306"        # kui 3306 on kinni, pane "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resto_app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: Europe/Tallinn
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
